// AUTO-GENERATED by Supabase CLI. DO NOT EDIT:
// npx supabase gen types typescript --project-id "zfznuscqncvujhzjzinc" --schema public > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      attendance: {
        Row: {
          class_id: string
          created_at: string | null
          date: string
          id: string
          notes: string | null
          recorded_by: string | null
          status: string
          student_id: string
          updated_at: string | null
        }
        Insert: {
          class_id: string
          created_at?: string | null
          date: string
          id?: string
          notes?: string | null
          recorded_by?: string | null
          status: string
          student_id: string
          updated_at?: string | null
        }
        Update: {
          class_id?: string
          created_at?: string | null
          date?: string
          id?: string
          notes?: string | null
          recorded_by?: string | null
          status?: string
          student_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'attendance_class_id_fkey'
            columns: ['class_id']
            isOneToOne: false
            referencedRelation: 'classes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'attendance_recorded_by_fkey'
            columns: ['recorded_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'attendance_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          created_at: string | null
          details: Json | null
          entity: string
          entity_id: string | null
          id: string
          staff_id: string | null
        }
        Insert: {
          action: string
          created_at?: string | null
          details?: Json | null
          entity: string
          entity_id?: string | null
          id?: string
          staff_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string | null
          details?: Json | null
          entity?: string
          entity_id?: string | null
          id?: string
          staff_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'audit_log_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
        ]
      }
      classes: {
        Row: {
          academic_year: string
          active: boolean
          created_at: string | null
          id: string
          name: string
          room_number: string | null
          teacher_id: string | null
          year_group: string
        }
        Insert: {
          academic_year?: string
          active?: boolean
          created_at?: string | null
          id?: string
          name: string
          room_number?: string | null
          teacher_id?: string | null
          year_group: string
        }
        Update: {
          academic_year?: string
          active?: boolean
          created_at?: string | null
          id?: string
          name?: string
          room_number?: string | null
          teacher_id?: string | null
          year_group?: string
        }
        Relationships: [
          {
            foreignKeyName: 'classes_teacher_id_fkey'
            columns: ['teacher_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
        ]
      }
      guardians: {
        Row: {
          address_line_1: string | null
          address_line_2: string | null
          city: string | null
          created_at: string | null
          email: string | null
          first_name: string
          id: string
          last_name: string
          notes: string | null
          phone: string
          postcode: string | null
          updated_at: string | null
        }
        Insert: {
          address_line_1?: string | null
          address_line_2?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          first_name: string
          id?: string
          last_name: string
          notes?: string | null
          phone: string
          postcode?: string | null
          updated_at?: string | null
        }
        Update: {
          address_line_1?: string | null
          address_line_2?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          first_name?: string
          id?: string
          last_name?: string
          notes?: string | null
          phone?: string
          postcode?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      incidents: {
        Row: {
          created_at: string
          created_by: string
          description: string
          id: string
          incident_date: string
          parent_notified: boolean
          parent_notified_at: string | null
          student_id: string
          title: string
          type: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by: string
          description: string
          id?: string
          incident_date: string
          parent_notified?: boolean
          parent_notified_at?: string | null
          student_id: string
          title: string
          type: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string
          description?: string
          id?: string
          incident_date?: string
          parent_notified?: boolean
          parent_notified_at?: string | null
          student_id?: string
          title?: string
          type?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'incidents_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'incidents_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'incidents_updated_by_fkey'
            columns: ['updated_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
        ]
      }
      lesson_plans: {
        Row: {
          class_id: string
          created_at: string
          created_by: string
          description: string
          id: string
          lesson_date: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          class_id: string
          created_at?: string
          created_by: string
          description: string
          id?: string
          lesson_date: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          class_id?: string
          created_at?: string
          created_by?: string
          description?: string
          id?: string
          lesson_date?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'lesson_plans_class_id_fkey'
            columns: ['class_id']
            isOneToOne: false
            referencedRelation: 'classes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'lesson_plans_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'lesson_plans_updated_by_fkey'
            columns: ['updated_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
        ]
      }
      photo_consent_opt_outs: {
        Row: {
          actioned_at: string | null
          actioned_by: string | null
          child_first_name: string
          child_last_name: string
          created_at: string
          date_of_birth: string
          declaration_name: string
          id: string
          notes: string | null
          rejected_reason: string | null
          status: Database['public']['Enums']['photo_opt_out_status']
          student_id: string | null
          submitted_at: string
          updated_at: string
        }
        Insert: {
          actioned_at?: string | null
          actioned_by?: string | null
          child_first_name: string
          child_last_name: string
          created_at?: string
          date_of_birth: string
          declaration_name: string
          id?: string
          notes?: string | null
          rejected_reason?: string | null
          status?: Database['public']['Enums']['photo_opt_out_status']
          student_id?: string | null
          submitted_at?: string
          updated_at?: string
        }
        Update: {
          actioned_at?: string | null
          actioned_by?: string | null
          child_first_name?: string
          child_last_name?: string
          created_at?: string
          date_of_birth?: string
          declaration_name?: string
          id?: string
          notes?: string | null
          rejected_reason?: string | null
          status?: Database['public']['Enums']['photo_opt_out_status']
          student_id?: string | null
          submitted_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'photo_consent_opt_outs_actioned_by_fkey'
            columns: ['actioned_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'photo_consent_opt_outs_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string | null
          endpoint: string
          id: string
          p256dh: string
          staff_id: string
        }
        Insert: {
          auth: string
          created_at?: string | null
          endpoint: string
          id?: string
          p256dh: string
          staff_id: string
        }
        Update: {
          auth?: string
          created_at?: string | null
          endpoint?: string
          id?: string
          p256dh?: string
          staff_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'push_subscriptions_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
        ]
      }
      registration_submission_contacts: {
        Row: {
          address_line_1: string | null
          address_line_2: string | null
          city: string | null
          contact_role: Database['public']['Enums']['contact_role']
          created_at: string
          email: string | null
          first_name: string
          id: string
          last_name: string
          phone: string
          postcode: string | null
          relationship: string | null
          same_as_child_address: boolean
          submission_id: string
        }
        Insert: {
          address_line_1?: string | null
          address_line_2?: string | null
          city?: string | null
          contact_role: Database['public']['Enums']['contact_role']
          created_at?: string
          email?: string | null
          first_name: string
          id?: string
          last_name: string
          phone: string
          postcode?: string | null
          relationship?: string | null
          same_as_child_address?: boolean
          submission_id: string
        }
        Update: {
          address_line_1?: string | null
          address_line_2?: string | null
          city?: string | null
          contact_role?: Database['public']['Enums']['contact_role']
          created_at?: string
          email?: string | null
          first_name?: string
          id?: string
          last_name?: string
          phone?: string
          postcode?: string | null
          relationship?: string | null
          same_as_child_address?: boolean
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'registration_submission_contacts_submission_id_fkey'
            columns: ['submission_id']
            isOneToOne: false
            referencedRelation: 'registration_submissions'
            referencedColumns: ['id']
          },
        ]
      }
      registration_submissions: {
        Row: {
          actioned_at: string | null
          actioned_by: string | null
          address_line_1: string
          address_line_2: string | null
          allergies: string | null
          child_first_name: string
          child_last_name: string
          city: string
          collect_authorised: string | null
          collect_password: string | null
          consent_comms_email_sms: boolean
          consent_emergency_first_aid: boolean
          consent_home_school: boolean
          consent_photo_media: boolean
          consent_privacy_notice: boolean
          created_at: string
          date_of_birth: string
          declaration_name: string
          id: string
          linked_existing: boolean
          medical_details: string | null
          postcode: string
          preferred_year_group: string | null
          rejected_reason: string | null
          status: Database['public']['Enums']['submission_status']
          student_id: string | null
          submitted_at: string
          updated_at: string
        }
        Insert: {
          actioned_at?: string | null
          actioned_by?: string | null
          address_line_1: string
          address_line_2?: string | null
          allergies?: string | null
          child_first_name: string
          child_last_name: string
          city: string
          collect_authorised?: string | null
          collect_password?: string | null
          consent_comms_email_sms?: boolean
          consent_emergency_first_aid?: boolean
          consent_home_school?: boolean
          consent_photo_media?: boolean
          consent_privacy_notice?: boolean
          created_at?: string
          date_of_birth: string
          declaration_name: string
          id?: string
          linked_existing?: boolean
          medical_details?: string | null
          postcode: string
          preferred_year_group?: string | null
          rejected_reason?: string | null
          status?: Database['public']['Enums']['submission_status']
          student_id?: string | null
          submitted_at?: string
          updated_at?: string
        }
        Update: {
          actioned_at?: string | null
          actioned_by?: string | null
          address_line_1?: string
          address_line_2?: string | null
          allergies?: string | null
          child_first_name?: string
          child_last_name?: string
          city?: string
          collect_authorised?: string | null
          collect_password?: string | null
          consent_comms_email_sms?: boolean
          consent_emergency_first_aid?: boolean
          consent_home_school?: boolean
          consent_photo_media?: boolean
          consent_privacy_notice?: boolean
          created_at?: string
          date_of_birth?: string
          declaration_name?: string
          id?: string
          linked_existing?: boolean
          medical_details?: string | null
          postcode?: string
          preferred_year_group?: string | null
          rejected_reason?: string | null
          status?: Database['public']['Enums']['submission_status']
          student_id?: string | null
          submitted_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'registration_submissions_actioned_by_fkey'
            columns: ['actioned_by']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'registration_submissions_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          },
        ]
      }
      staff: {
        Row: {
          contact_number: string | null
          created_at: string | null
          display_name: string | null
          email: string
          first_name: string
          id: string
          last_name: string
          personal_email: string | null
          role: string
        }
        Insert: {
          contact_number?: string | null
          created_at?: string | null
          display_name?: string | null
          email: string
          first_name: string
          id?: string
          last_name: string
          personal_email?: string | null
          role: string
        }
        Update: {
          contact_number?: string | null
          created_at?: string | null
          display_name?: string | null
          email?: string
          first_name?: string
          id?: string
          last_name?: string
          personal_email?: string | null
          role?: string
        }
        Relationships: []
      }
      staff_attendance: {
        Row: {
          created_at: string | null
          date: string
          id: string
          signed_in_at: string
          signed_out_at: string | null
          staff_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          date?: string
          id?: string
          signed_in_at: string
          signed_out_at?: string | null
          staff_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          date?: string
          id?: string
          signed_in_at?: string
          signed_out_at?: string | null
          staff_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'staff_attendance_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
        ]
      }
      student_classes: {
        Row: {
          class_id: string
          enrolled_at: string | null
          id: string
          student_id: string
        }
        Insert: {
          class_id: string
          enrolled_at?: string | null
          id?: string
          student_id: string
        }
        Update: {
          class_id?: string
          enrolled_at?: string | null
          id?: string
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'student_classes_class_id_fkey'
            columns: ['class_id']
            isOneToOne: false
            referencedRelation: 'classes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'student_classes_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          },
        ]
      }
      students: {
        Row: {
          active: boolean
          additional_contact_1_id: string | null
          additional_contact_1_relationship: string | null
          additional_contact_2_id: string | null
          additional_contact_2_relationship: string | null
          address_guardian_id: string | null
          address_line_1: string | null
          address_line_2: string | null
          allergies: string | null
          city: string | null
          consent_comms_email_sms: boolean
          consent_emergency_first_aid: boolean
          consent_home_school: boolean
          consent_photo_media: boolean
          consent_privacy_notice: boolean
          created_at: string | null
          date_of_birth: string | null
          enrollment_date: string | null
          first_name: string
          id: string
          last_name: string
          medical_details: string | null
          notes: string | null
          postcode: string | null
          primary_guardian_id: string
          primary_guardian_relationship: string | null
          secondary_guardian_id: string | null
          secondary_guardian_relationship: string | null
          student_code: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean
          additional_contact_1_id?: string | null
          additional_contact_1_relationship?: string | null
          additional_contact_2_id?: string | null
          additional_contact_2_relationship?: string | null
          address_guardian_id?: string | null
          address_line_1?: string | null
          address_line_2?: string | null
          allergies?: string | null
          city?: string | null
          consent_comms_email_sms?: boolean
          consent_emergency_first_aid?: boolean
          consent_home_school?: boolean
          consent_photo_media?: boolean
          consent_privacy_notice?: boolean
          created_at?: string | null
          date_of_birth?: string | null
          enrollment_date?: string | null
          first_name: string
          id?: string
          last_name: string
          medical_details?: string | null
          notes?: string | null
          postcode?: string | null
          primary_guardian_id: string
          primary_guardian_relationship?: string | null
          secondary_guardian_id?: string | null
          secondary_guardian_relationship?: string | null
          student_code?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean
          additional_contact_1_id?: string | null
          additional_contact_1_relationship?: string | null
          additional_contact_2_id?: string | null
          additional_contact_2_relationship?: string | null
          address_guardian_id?: string | null
          address_line_1?: string | null
          address_line_2?: string | null
          allergies?: string | null
          city?: string | null
          consent_comms_email_sms?: boolean
          consent_emergency_first_aid?: boolean
          consent_home_school?: boolean
          consent_photo_media?: boolean
          consent_privacy_notice?: boolean
          created_at?: string | null
          date_of_birth?: string | null
          enrollment_date?: string | null
          first_name?: string
          id?: string
          last_name?: string
          medical_details?: string | null
          notes?: string | null
          postcode?: string | null
          primary_guardian_id?: string
          primary_guardian_relationship?: string | null
          secondary_guardian_id?: string | null
          secondary_guardian_relationship?: string | null
          student_code?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'students_additional_contact_1_id_fkey'
            columns: ['additional_contact_1_id']
            isOneToOne: false
            referencedRelation: 'guardians'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'students_additional_contact_2_id_fkey'
            columns: ['additional_contact_2_id']
            isOneToOne: false
            referencedRelation: 'guardians'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'students_address_guardian_id_fkey'
            columns: ['address_guardian_id']
            isOneToOne: false
            referencedRelation: 'guardians'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'students_primary_guardian_id_fkey'
            columns: ['primary_guardian_id']
            isOneToOne: false
            referencedRelation: 'guardians'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'students_secondary_guardian_id_fkey'
            columns: ['secondary_guardian_id']
            isOneToOne: false
            referencedRelation: 'guardians'
            referencedColumns: ['id']
          },
        ]
      }
      timetable_slots: {
        Row: {
          class_id: string
          created_at: string | null
          day_of_week: string
          end_time: string
          id: string
          notes: string | null
          room: string | null
          start_time: string
          subject: string | null
        }
        Insert: {
          class_id: string
          created_at?: string | null
          day_of_week: string
          end_time: string
          id?: string
          notes?: string | null
          room?: string | null
          start_time: string
          subject?: string | null
        }
        Update: {
          class_id?: string
          created_at?: string | null
          day_of_week?: string
          end_time?: string
          id?: string
          notes?: string | null
          room?: string | null
          start_time?: string
          subject?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'timetable_slots_class_id_fkey'
            columns: ['class_id']
            isOneToOne: false
            referencedRelation: 'classes'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      apply_photo_opt_out: {
        Args: { p_request_id: string; p_staff_id: string; p_student_id: string }
        Returns: string
      }
      approve_registration: {
        Args: {
          p_class_id?: string
          p_existing_student_id?: string
          p_reuse_guardians?: boolean
          p_staff_id: string
          p_student_code?: string
          p_submission_id: string
        }
        Returns: string
      }
      create_registration_submission: {
        Args: { p_contacts: Json; p_submission: Json }
        Returns: string
      }
      find_guardian_matches: {
        Args: { p_email: string; p_last_name: string; p_phone: string }
        Returns: {
          email: string
          first_name: string
          id: string
          last_name: string
          matched_on: string
          phone: string
        }[]
      }
      find_student_matches: {
        Args: {
          p_date_of_birth: string
          p_first_name: string
          p_last_name: string
        }
        Returns: {
          active: boolean
          date_of_birth: string
          first_name: string
          id: string
          last_name: string
          student_code: string
        }[]
      }
      get_attendance_summary: {
        Args: { p_date: string }
        Returns: {
          class_id: string
          max_updated_at: string
          min_created_at: string
          present_count: number
        }[]
      }
      migrate_class: {
        Args: {
          p_academic_year: string
          p_name: string
          p_room_number: string
          p_source_class_id: string
          p_teacher_id: string
          p_year_group: string
        }
        Returns: Json
      }
    }
    Enums: {
      contact_role: 'primary' | 'secondary' | 'additional_1' | 'additional_2'
      photo_opt_out_status: 'pending' | 'actioned' | 'rejected'
      submission_status: 'pending' | 'actioned' | 'rejected'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      contact_role: ['primary', 'secondary', 'additional_1', 'additional_2'],
      photo_opt_out_status: ['pending', 'actioned', 'rejected'],
      submission_status: ['pending', 'actioned', 'rejected'],
    },
  },
} as const
