// Writes public/sw.js from scripts/sw.template.js.
//
//   node scripts/build-sw.mjs        after `next build`
//   node scripts/build-sw.mjs --dev  before `next dev` (no precache, no caching)
//
// The cache name is a hash of the build's asset names (content-hashed by Next),
// the static precache files and the template, so any change to what the worker
// serves produces a new sw.js, which is what makes the browser install the new
// worker on the next visit.

import { createHash } from 'node:crypto'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const isDev = process.argv.includes('--dev')
const root = join(import.meta.dirname, '..')
const nextDir = join(root, '.next')

// Served from public/; installing the worker fails if any is missing.
const STATIC_PRECACHE = [
  '/manifest.json',
  '/offline.html',
  '/icons/portal-icon-192.png',
]

async function listFiles(dir) {
  try {
    return (await readdir(dir, { recursive: true }))
      .map((f) => f.split('\\').join('/'))
      .sort()
  } catch (err) {
    if (err.code === 'ENOENT') return []
    throw err
  }
}

async function buildConstants(template) {
  if (isDev) return { cacheName: 'hshb-portal-dev', precache: [] }

  const chunkFiles = await listFiles(join(nextDir, 'static/chunks'))
  if (chunkFiles.length === 0) {
    throw new Error(
      'No build output in .next/static/chunks — run `next build` first.',
    )
  }
  const mediaFiles = await listFiles(join(nextDir, 'static/media'))

  const hash = createHash('sha256')
    .update(chunkFiles.join('\n'))
    .update(mediaFiles.join('\n'))
    .update(template)
  for (const path of STATIC_PRECACHE) {
    hash.update(await readFile(join(root, 'public', path)))
  }

  // Only what every page loads: the runtime, polyfills and the stylesheets.
  // Route chunks are cached the first time they are fetched.
  const buildManifest = JSON.parse(
    await readFile(join(nextDir, 'build-manifest.json'), 'utf8'),
  )
  const precache = [
    ...buildManifest.rootMainFiles,
    ...buildManifest.polyfillFiles,
    ...chunkFiles
      .filter((f) => f.endsWith('.css'))
      .map((f) => `static/chunks/${f}`),
  ].map((f) => `/_next/${f.split('\\').join('/')}`)

  return {
    cacheName: `hshb-portal-${hash.digest('hex').slice(0, 8)}`,
    precache: [...new Set(precache)],
  }
}

const template = await readFile(join(root, 'scripts/sw.template.js'), 'utf8')
const { cacheName, precache } = await buildConstants(template)

await writeFile(
  join(root, 'public/sw.js'),
  [
    '// Generated by scripts/build-sw.mjs; edit scripts/sw.template.js instead.',
    `const CACHE_NAME = ${JSON.stringify(cacheName)}`,
    `const STATIC_PRECACHE = ${JSON.stringify(STATIC_PRECACHE, null, 2)}`,
    `const BUILD_PRECACHE = ${JSON.stringify(precache, null, 2)}`,
    `const IS_DEV = ${isDev}`,
    '',
    template,
  ].join('\n'),
)

console.log(
  `Wrote public/sw.js (${precache.length} precached assets, cache ${cacheName})`,
)
