// Writes public/sw.js from scripts/sw.template.js.
//
//   node scripts/build-sw.mjs        after `next build`
//   node scripts/build-sw.mjs --dev  before `next dev` (no precache, no caching)
//
// The cache name is a hash of every chunk file name. Chunk names are content
// hashes, so any code change produces a new sw.js, which is what makes the
// browser install the new worker on the next visit.

import { createHash } from 'node:crypto'
import { readFile, readdir, writeFile } from 'node:fs/promises'

const isDev = process.argv.includes('--dev')

async function buildConstants() {
  if (isDev) return { cacheName: 'hshb-portal-dev', precache: [] }

  const chunkFiles = (
    await readdir('.next/static/chunks', { recursive: true })
  ).sort()
  const hash = createHash('sha256')
    .update(chunkFiles.join('\n'))
    .digest('hex')
    .slice(0, 8)

  // Only what every page loads: the runtime, polyfills and the stylesheets.
  // Route chunks are cached the first time they are fetched.
  const buildManifest = JSON.parse(
    await readFile('.next/build-manifest.json', 'utf8'),
  )
  const precache = [
    ...buildManifest.rootMainFiles,
    ...buildManifest.polyfillFiles,
    ...chunkFiles
      .filter((f) => f.endsWith('.css'))
      .map((f) => `static/chunks/${f}`),
  ].map((f) => `/_next/${f.split('\\').join('/')}`)

  return { cacheName: `hshb-portal-${hash}`, precache: [...new Set(precache)] }
}

const { cacheName, precache } = await buildConstants()
const template = await readFile('scripts/sw.template.js', 'utf8')

await writeFile(
  'public/sw.js',
  [
    '// Generated by scripts/build-sw.mjs; edit scripts/sw.template.js instead.',
    `const CACHE_NAME = ${JSON.stringify(cacheName)}`,
    `const BUILD_PRECACHE = ${JSON.stringify(precache, null, 2)}`,
    `const IS_DEV = ${isDev}`,
    '',
    template,
  ].join('\n'),
)

console.log(
  `Wrote public/sw.js (${precache.length} precached assets, cache ${cacheName})`,
)
