#!/usr/bin/env bash
# Regenerate src/types/database.ts from the local Supabase instance.
# The CLI overwrites the file; this script prepends the repo header comment so
# the generation command stays documented in the file itself.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/types/database.ts"
HEADER='// AUTO-GENERATED by Supabase CLI. DO NOT EDIT:
// npx supabase gen types typescript --project-id "zfznuscqncvujhzjzinc" --schema public > src/types/database.ts'

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

npx supabase gen types typescript --local --schema public >"$TMP"
{
  printf '%s\n\n' "$HEADER"
  cat "$TMP"
} >"$OUT"

echo "Wrote $OUT (header comment preserved)"
